### ISSUE TITLE
Permission not restricted on older apps

### ISSUE THREAD

**Issue by packetup** [RattlesnakeOS/community_patches#5] opened 2018-11-30 23:25 UTC
**Specific plugin(s):**
[X] 00001-global-internet-permission-toggle.patch
[X] 00002-global-sensors-permission-toggle.patch

Currently unable to restrict internet or sensor permission on apps that target sdk version 22 or lower.

**Comment by stevesoltys** [comment] 2018-11-30 23:35
Do you mean the app isn't listed, or the permission toggle doesn't affect the app?

**Comment by packetup** [comment] 2018-12-01 00:00
It is not affected. A warning appears as it should: "This app was designed for an older version of Android. Denying permission may cause it to no longer function as intended." After selecting "DENY ANYWAY" the permission will be shown as disabled. Later revisiting the menu shows the permission was not revoked.

**Comment by stevesoltys** [comment] 2018-12-04 02:18
I can reproduce this, but I don't think I'll have time to look into it for a couple weeks.

You might be able to resolve the issue by porting the following changes to Android Pie:

https://github.com/AndroidHardeningArchive/platform_packages_apps_PackageInstaller/commit/d4cc88341d19ad4af37216fdf8ad7b8c77f985b6
https://github.com/AndroidHardeningArchive/platform_packages_apps_PackageInstaller/commit/9590f1f79220e2a813726129a07ed4dfa519f58d
https://github.com/AndroidHardeningArchive/platform_packages_apps_PackageInstaller/commit/3b2bd41a541a1f6fa85fa96b93df33b49f6df610
https://github.com/AndroidHardeningArchive/platform_packages_apps_PackageInstaller/commit/d15024c558fbd81046cb845e9ab0f1167fd4a146
https://github.com/AndroidHardeningArchive/platform_packages_apps_PackageInstaller/commit/0ccde5f50b8cfa9a66b655b3b14d77c58944a081

**Comment by thestinger** [comment] 2019-03-17 15:38
Yes, the frameworks/base changes are not enough. There's an implementation of these and other features for Android Pie as part of the new AndroidHardening project at https://github.com/AndroidHardening with releases at https://seamlessupdate.app/.

**Comment by thestinger** [comment] 2019-03-17 15:39
Yes, the frameworks/base changes are not enough. There's an implementation of these and other features for Android Pie as part of the new AndroidHardening project at https://github.com/AndroidHardening with releases at https://seamlessupdate.app/. These will be in the next stable release, among other new improvements and restored past features.

**Comment by thestinger** [comment] 2019-03-17 15:56
The frameworks/base changes aren't the full implementation of these features. I recommend using the current [GrapheneOS project](https://github.com/GrapheneOS) which has working implementations of these features and many others, including much deeper changes like the [next generation hardened allocator](https://github.com/GrapheneOS/hardened_malloc). It's not realistic to maintain all of these changes as a few patch files without dedicated maintainers and regular testing for each release.

There are tagged stable releases for the GrapheneOS project along with official releases at https://grapheneos.org/releases/ that are compatible with the [Auditor app](https://github.com/GrapheneOS/Auditor) and https://attestation.app/ service (https://github.com/GrapheneOS/AttestationServer). It will soon have a proper name and documentation as it did in the past, and will be slowly expanding into a larger project with a proper development team.

I would recommend against expending effort trying to extract a few tiny portions of the project piece by piece rather than using it as a whole. It's going to be a needless duplication of effort which could be going towards porting features to Android Pie in the GrapheneOS project itself along with turning more of the designs for planned features into reality and coming up with entirely new features. It's not a viable project with only one developer, since it's very broad with many areas requiring deep and sometimes invasive changes. It's all going to need to be ported to Android Q in a few months too, so the project is going to need to be better resourced with more of a development team to make it through that.

**Comment by stevesoltys** [comment] 2019-03-17 17:44
I think these projects have different goals, so I don't think it's "a needless duplication of effort". RattlesnakeOS was never meant to have all of the features your hardening projects have. It's just stock AOSP with the option to make small changes like this.

**Comment by thestinger** [comment] 2019-03-17 18:13
The INTERNET permission toggle is going to become substantially larger since making it truly work requires many changes elsewhere like Chromium. The SENSORS permission can actually be limited to the 2 patches in frameworks/base and the 2 in packages/apps/PackageInstaller.

I do think having different groups of people extending the same features, porting forwards to new Android versions, identifying the same compatibility issues, missing scope (applies quite a bit to INTERNET), bugs, etc. is a needless duplication of effort.

**Comment by dan-v** [comment] 2019-03-17 21:40
@thestinger - these are community driven patches and aren't meant to be fully baked features, hence why they are just patches and not part of the standard RattlesnakeOS build process. For anyone that finds them useful (I do), they can pull them into their builds. If you would like to setup a more formal repository of patches or do some sort of collaboration on this front I'd be open to it. I think the two project goals are a bit different though as @stevesoltys mentioned, as RattlesnakeOS is really just focused on building plain AOSP for Pixel devices and then provides a mechanism to opt in to additional tweaks, whereas your project would likely just bake those changes into the build process.

**Comment by dan-v** [comment] 2020-02-01 03:57
Not planning on looking into this. Closing this out.

**Closed as completed by dan-v** 2020-02-01 03:57 UTC
